version: '3.3'
services:
  mysql-master:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - ${DB1_PORT}:3306
    networks:
      - mysql
    volumes:
      - ./data01:/var/lib/mysql

volumes:
  data01:
    driver: local
  data02:
    driver: local

networks:
  mysql:
    driver: bridge
